version: '2'
services:
  nexgddp-process-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./data:/opt/nexgddp-data-prep/data"
    extra_hosts:
      - "mymachine:192.168.1.42"
